Fatec.ProjetoAnimais/Fatec.ProjetoAnimais/Controllers/PessoaController.cs
using Fatec.ProjetoAnimais.DB.Contexto;
using Fatec.ProjetoAnimais.DB.Entitidades;
using Fatec.ProjetoAnimais.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Fatec.ProjetoAnimais.Controllers
{
    public class PessoaController : Controller
    {
        // GET: Release
        public ActionResult Index()
        {
            using (AutismoContext context = new AutismoContext())
            {
                var listDB = context.Pessoa.OrderBy(x => x.id).ToList();
                var listViewModel = new List<PessoaViewModel>();
                listDB.ForEach(x => listViewModel.Add(new PessoaViewModel
                {
                    id = x.id,
                    cpf = x.cpf,
                    email = x.email,
                    nome = x.nome,
                    sobrenome = x.sobrenome,
                    datanasc = x.datanasc,
                    senha = x.senha,
                    perfil = x.perfil
                }));

                return View(listViewModel);
            }
        }

        // GET: Release/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Release/Create
        [HttpPost]
        public ActionResult Create(PessoaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                using (AutismoContext context = new AutismoContext())
                {
                    Pessoa pessoa = new Pessoa
                    {
                        id = model.id,
                        cpf = model.cpf,
                        email = model.email,
                        nome = model.nome,
                        sobrenome = model.sobrenome,
                        datanasc = model.datanasc,
                        senha = model.senha,
                        perfil = model.perfil

                    };

                    context.Pessoa.Add(pessoa);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        // POST: Release/Createl(Cat


        // GET: Release/Edit/5
        public ActionResult Edit(int id)
        {
            using (AutismoContext context = new AutismoContext())
            {
                var db = context.Pessoa.Find(id);
                    
                PessoaViewModel model = new PessoaViewModel
                {
                    id = db.id,
                    cpf = db.cpf,
                    email = db.email,
                    nome = db.nome,
                    sobrenome = db.sobrenome,
                    datanasc = db.datanasc,
                    senha = db.senha,
                    perfil = db.perfil

                };
                return View(model);
            }
        }

        // POST: Release/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PessoaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                using (AutismoContext context = new AutismoContext())
                {
                    var db = context.Pessoa.Find(id);
                    if (db == null)
                    {
                        ModelState.AddModelError("", "Pessoa não encontrada!");
                        return View(model);
                    }
                    db.cpf = model.cpf;
                    db.email = model.email;
                    db.nome = model.nome;
                    db.sobrenome = model.sobrenome;
                    db.datanasc = model.datanasc;
                    db.senha = model.senha;
                    db.perfil = model.perfil;

                    context.Entry(db).State = EntityState.Modified;
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        // GET: Release/Delete/5
        public ActionResult Delete(int id)
        {
            using (AutismoContext context = new AutismoContext())
            {
                var db = context.Pessoa.Find(id);

                PessoaViewModel model = new PessoaViewModel
                {
                    id = db.id,
                    cpf = db.cpf,
                    email = db.email,
                    nome = db.nome,
                    sobrenome = db.sobrenome,
                    datanasc = db.datanasc,
                    senha = db.senha,
                    perfil = db.perfil

                };

                return View(model);
            }
        }

        // POST: Release/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, PessoaViewModel model)
        {
            try
            {
                using (AutismoContext context = new AutismoContext())
                {
                    var db = context.Pessoa.Find(id);
                    if (db == null)
                    {
                        ModelState.AddModelError("", "Pessoa não encontrada!");
                        return View(model);
                    }

                    context.Pessoa.Remove(db);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }
    }
}

Fatec.ProjetoAnimais/Fatec.ProjetoAnimais/Views/Shared/_Layout.cshtml
@using Fatec.ProjetoAnimais.Models
@using Fatec.ProjetoAnimais.Sessao
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aprendendo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dataTable")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>


    @if (ControleSessao.UsuarioLogado?.perfil == (int)PessoaViewModel.ePerfil.Professor)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("DashBoard", "IndexAdmin", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Gestão de pessoas", "Index", "Pessoa")</li>
                        <li>@Html.ActionLink("Gestão de Atividades", "Index", "Atividade")</li>
                        @*<li>@Html.ActionLink("Doações", "Index", "Doacoes")</li>*@
                        @*<li>@Html.ActionLink("Relatórios", "Index", "Relatorio")</li>*@


                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Página Inicial", "IndexUsuario", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    @*<ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Manutenção de pessoas", "Index", "Pessoa")</li>
                            <li>@Html.ActionLink("Manutenção de animais", "Index", "Animal")</li>
                        </ul>*@
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    }

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aprendendo</p>
        </footer>
    </div>
    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Fatec.ProjetoAnimais/Fatec.ProjetoAnimais/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aprendendo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/dataTable")
    @Scripts.Render("~/bundles/bootstrap")

</head>

<style>
    footer {
        margin: 0 130px 10px;

    }

</style>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aprendendo</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>